### ISSUE TITLE
MailboxProcessor stops processing after 667 Post messages

### ISSUE THREAD

**Issue by jbeeko** [fable-compiler/Fable#1722]
### Description 
For up to 667 `Post` messages to a Mailbox the messages are processed. There is a test for the first `Post`  here https://github.com/fable-compiler/Fable/blob/99f170e186221127385a49f7f5d8bd6d83c65042/tests/Main/AsyncTests.fs#L249 

However after 667 post messages I suspect this assertion will fail. 

### Repo code
You can reproduce this in the REPL with the following code (a modification of the test referenced above):
```
let mutable res = None
let agent = new MailboxProcessor<int>(fun inbox ->
    let rec messageLoop() = async {
        let! msg = inbox.Receive()
        match msg with
        | 0 -> () // Finish loop
        | _ ->
            printfn "counting %i" msg
            res <- Some msg
            return! messageLoop()
    }
    messageLoop()
)
agent.Post(1)
agent.Start()
let max = 669
[1..max] |> List.iter (fun i  -> 
  agent.Post(i)
  printfn "res is: %A" res
   )
```

### Expected and actual result
Here is the output from the console. Notice how up to 666 the `printfn` for `counting` and `res` are interleaved. Once there have been 667 `Post` messages the processing stops and it is only until the test ends that they are consumed. Note: he log shows this at 666 rather than 667 because the initial `Post(1)` before the processor is started counts against the total of 667. 

I would expect the pattern of interleaving to continue.

This happens not only on the REPL but also when the code is deployed as a CloudflareWorker. 

```
counting 1
res is: 1
counting 2
res is: 2
counting 3
res is: 3
counting 4
res is: 4
...
counting 665
res is: 665
counting 666
res is: 666
res is: 666
res is: 666
res is: 666
counting 667
counting 668
counting 669
```

Finally here is a unit that that I believe will demonstrate the issue:
```
    testCaseAsync "MailboxProcessor.post works for many posts" <| fun () ->
        async {
            let mutable res = None
            let agent = new MailboxProcessor<int>(fun inbox ->
                let rec messageLoop() = async {
                    let! msg = inbox.Receive()
                    match msg with
                    | 0 -> () // Finish loop
                    | _ ->
                        //printfn "counting %i" msg
                        res <- Some msg
                        return! messageLoop()
                }
                messageLoop()
            )
            agent.Post(1)
            equal None res
            agent.Start()
            let max = 4
            [1..max] |> List.iter (fun i  -> 
              agent.Post(i)
              // Not necessary in the JS implementation, but in .NET
              // MailboxProcessor works in the background so we must wait a bit
              do! Async.Sleep 200
              //printfn "res is: %A" res
              equal Some i
              )
            agent.Post(0)
            equal (Some max) res  // Mailbox has finished
        }
```

**Comment by jbeeko** [comment]
Actually the following simple mod to https://github.com/fable-compiler/Fable/blob/99f170e186221127385a49f7f5d8bd6d83c65042/tests/Main/AsyncTests.fs#L228

will demonstrate the issue:


```
    testCaseAsync "MailboxProcessor.post works" <| fun () ->
        async {
            let mutable res = None
            let agent = new MailboxProcessor<int>(fun inbox ->
                let rec messageLoop() = async {
                    let! msg = inbox.Receive()
                    match msg with
                    | 3 -> () // Finish loop
                    | _ ->
                        res <- Some msg
                        return! messageLoop()
                }
                messageLoop()
            )
           //agent.Post(1)
           [1..667] |> List.iter (fun i -> agent.Post(1)). //<===============================
           equal None res // Mailbox hasn't started yet
            agent.Start()
            agent.Post(2)
            // Not necessary in the JS implementation, but in .NET
            // MailboxProcessor works in the background so we must wait a bit
            do! Async.Sleep 200
            equal (Some 2) res
            agent.Post(3)
            equal (Some 2) res  // Mailbox has finished
        }
```

**Comment by alfonsogarciacaro** [comment]
[You found the number of the beast!](https://youtu.be/dx5KnFr9xSk) ;)

TBH I don't know well the implementation of MailboxProcessor in Fable as it was originally contributed by Tomas Petricek and I haven't touched it since. Not sure why it's stopping at this ominous number, but in any case, although we have this simple test to check the `Post` method, you shouldn't rely in effects applied from a MailboxProcessor **to the outside** as this defeats the purpose of the actor, which is to keep **internal state** and communicate with the outside only through messages.

In your first example ☝️ the correlation between the two printfn statements is not deterministic in .NET either.

**Comment by ncave** [comment]
@alfonsogarciacaro Yeah, that actor must be an Iron Maiden fan, old skool :) At least it's not stopping after [616](https://en.wikipedia.org/wiki/Number_of_the_Beast#616)...

**Comment by jbeeko** [comment]
@alfonsogarciacaro I understand that the progress through the messages is non-deterministic but it should be making some progress. I believe it is not making any. I have deployed a worker and after 667 messages it seems to stop. I've waited several minutes and not observed any progress. This is problematic if using the Agent in the context of a Service or Web worker. 

I'll look at the implementation and see if anything stands out.

**Comment by alfonsogarciacaro** [comment]
As far as I can see, there's progress. The problem is having a print statement outside the actor's loop. The print statements within the actor is working correctly. If you need correlation between the actor's actions and its responses, you can use an [async workflow and `PostAndAsyncReply`](https://fable.io/repl/#?code=C4TwDgpgBAshDO8CGBzaBeKBLAdsKAVFAILwg4DGAShGADYgDCAFkjjhHQDy7AB8AKAF0I+VBDxRMHAO6wkWOgCMA9gA8ACgCcVFBPBVaucROL4AKAGYBXHNhyq1UALR8o7qAI9QA9D6gAMqIA5PBQALZIANbQ8MBIwNC8EFo4SHRQwCqZzNBIFFlaXh4i+OHW8UoiUHEJGFAADMXupVBaEBQR+uIBKipg5gCUUlBIZJRQAN7N3lClAIRQ5uHdaAA0bbQMLGwcdMOYuI4AdDR6WABuEEMz3rWJUFzONfEPANRdpmi3HmBavJY7AAiACSeBSaQy9wgAC4oABSLBAl51H7udr0JisdicU5bEDmaGDNGbYDWVKLFZfCC9fo3bwAXxmVOQaFpA2JxIEY3InWm3nEeGOAGV4lpgPSPJZDFAAPr2KAAbQAjMdjsqGpqALpQAAmKhJC02YUwguAxw0KjixBwutIvJomKstk2mJ2OIyrhJ3mVGwx22xe2Js1+-zwgKgQIAompEql0sawCocPBYQikcaBAyoAAfNz2ygisXAEHhFa6rB1IA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohVpU5fxEKyLDhA&css=Q).

**Comment by jbeeko** [comment]
Either I don't understand how this should work or I'm not explaining it well. Here is code with print statements showing when messages are posted and when they are executed:

```
let agent = new MailboxProcessor<int>(fun inbox ->
    let rec messageLoop i = async {
        let! msg = inbox.Receive()
        match msg with
        | 0 -> () // Finish loop
        | _ ->
            printfn "processing %i at %s" msg (System.DateTime.Now.ToString("hh:mm:ss"))
            return! messageLoop()
    }
    messageLoop()
)
agent.Start()

[1..670] |> List.iter (fun i  -> 
  printfn "posting: %i at %s" i (System.DateTime.Now.ToString("hh:mm:ss"))
  agent.Post(i)
  )

printfn "finished loop %s" (System.DateTime.Now.ToString("hh:mm:ss"))
[1..100000000] |> List.iter (fun i -> i.ToString() |> ignore)
printfn "finished delay %s" (System.DateTime.Now.ToString("hh:mm:ss"))
```

And the console output after running in the Fable REPL:
```
posting: 1 
...

posting: 665 at 09:37:53
processing 665 at 09:37:53
posting: 666 at 09:37:53
processing 666 at 09:37:53
posting: 667 at 09:37:53
processing 667 at 09:37:53
posting: 668 at 09:37:53
posting: 669 at 09:37:53
posting: 670 at 09:37:53
finished loop 09:37:53
finished delay 09:38:20
processing 668 at 09:38:41
processing 669 at 09:38:41
processing 670 at 09:38:41
```

My expectation was that the MailboxProcess would process messages as it when along. Perhaps not in any deterministic order, perhaps intermittently, but I assumed it would continuously work through them.  Initially this is true, but after posting 667 messages no further messages will be process until the script ends. Thats why I say no further progress is being made, after 667 post messages the agent will stop processing as it goes along and queue all work for later finally doing it all as the script ends.

I've tested this for up to 1 million messages. This took a while but the pattern held, the messages were queued but not execute until the end of the script. While running memory usage grew to exceeded 3 gig. This behaviour is consistent with a growing queue of messages. I was kinda impressed nothing failed :).

I have also seen this behaviour in a ServiceWorker processing HTTP requests. Again all works as expected until 667 requests are handled, then the messages don't seem to get processed. I don't know if they all got done at the end, I assume so. 

I've looked at the MailboxProcessor `.ts` file. It seems that each `receive`, `add`, and `post` is invoking [__processEvents](https://github.com/fable-compiler/Fable/blob/aaa8376f3fe9b835f2572be749041aa12672269f/src/js/fable-library/MailboxProcessor.ts#L64) and consequently items should be getting processed but that invocation does not seem to be doing anything.

**Comment by alfonsogarciacaro** [comment]
I wasn't very keen to add MailboxProcessor because its only purpose is to offer a thread-safe message queue and in JS it didn't make much sense because you only have one thread. However it was a contribution so I accepted in order to be able to emulate some F# patterns with Fable.

I'm still not sure why you're getting this behaviour. But I suspect MailboxProcessor is not the best fit for what you want to do in JS. If you need to perform an action and then send a message, using the `Observable` module with a broadcaster may work better as you don't need to worry about multiple threads in JS: [example](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSVolqB0AwsADYlgDGSAlsBAvgOKRgBO1F66Sc4UAQq2ABDACYVhyNgB4A5ABUAfAAoAlFAC86KDqjkke6lIhsEmqABEONOsNZxpjAK7VRAGigBJAPIAjBGwAbjIKiiqq2rqoaL5sUAAe+PLsAOYpcYGakbq6AGbArFDKANJgcABqwiROYMoA+m4kRigmrKrq1NBNxqZQosDZOUPdLWz43hAAcmDxBoGDnSisucIUYF5+AayBwr7kckpQAO7USAAWgznRqLGFdXX4ME7+FOyxhj2FWkM-emAGKRconMzlc+GmR1BojUl1+IxYrAYAEFRNDAa4PPDWhFfkMAN5QExHLxWBAgYAIXbkY6nC643HXW4JfCk8kBNTmLGmfAAJTQwGCynRonUAB9FFBqCkIAV1gBfLjofRQVBOJBU9asMBmDRQSZ0MBcAD0RqghC1whQUHO618QjEEikhV8aqgWqQTlY0FOUEkG38QQ16BNUAQwGO6wkEBlBiQqXShWiCEp6TMuSEqGtZ3WwDVCFchuVrzAlrAghE4kkSw5310yt85nLDqrbBhOWVyDsSBrsJ0ytQwni5gAHAAGUe9qAAbQAjPh8AP4gBdKDiqAAGWa+FOcWUuSc3p0AFoJZOciGAApsfKsTPCaCrGwPiDAm3QO0Vx0GU5n3RaszSEesDANEkq-joIDsBASC5NAABE-6SggABcUAAKRInBbrauBUC+Ek8attQ7SDA2yESj4AbbBq0h1IoHidqwSCKsqKDID27b-HhDHqkx5jFqWTaVk6MKDCGTwvG86xcoigzKjJM7mA2a6bIGexgPgCDPAgrzUO8e4HiqCApFAJ6TpBiywVAcHrp4MDyAAopMDk8jOqEALIwIw6HUFAPIOTA6GYUZJn-jidZcTJABMSmrhKqnUepmnabp+n7tAqDGaZijmVBMHwbZ9lOS5UUeV5Pl+QFQVYZloXahEYmmjAvEGB+zbIJ0KSDIx3YNWxvVAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohVpU5fxEKyLDhA&css=Q).

**Comment by jbeeko** [comment]
> But I suspect MailboxProcessor is not the best fit for what you want to do in JS.
Point taken, I was simply looking for a more interesting "Hello World" to deploy to CloudFlare Workers. I can easily do something else. Thank you for the suggestion.
 
>in order to be able to emulate some F# patterns with Fable.
I still think the issue is real and it and can't be used the way people might think. But perhaps it does not matter since as you say it does not make much sense in JS.

**Comment by bigjonroberts** [comment]
Alternatives are coming?
https://github.com/fable-compiler/Fable/tree/master/src/fable-standalone/src/Worker

**Comment by alfonsogarciacaro** [comment]
I just tried to compile the first example with Fable 3 and didn't see any problem. Maybe related: the `worker_threads` module was added related to the fable-node bindings, can this be used in Cloudflare? https://github.com/fable-compiler/fable-node/pull/27

**Comment by alfonsogarciacaro** [comment]
Closing as stale
