### ISSUE TITLE
Support for implicit yields

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/Fable#1911]
[The addition of implicit yields](https://devblogs.microsoft.com/dotnet/announcing-f-4-7/) sounds really nice for Fable, as sure enough they mentioned it. Is there a thread or issue I can track to see when Fable will support this functionality? Testing it this morning gave me compile errors.

**Comment by ncave** [comment]
Looks like the new language features were merged into `dotnet/fsharp` master yesterday but there are still some build issues. I can rebase to latest from it once it gets to green. It will be a new Fable compiler version, once it's released.

**Comment by ncave** [comment]
@alfonsogarciacaro `fcs-fable` is rebased to latest.

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! I'm getting an error when trying to build latest service_slim. Do you know what it could be?

```
     1>FSC : warning FS0075: The command-line option '--version' has been deprecated [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
     1>/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018: System.IO.IOException: The target file '/Users/alfonsogarciacaronunez/dev/fsharp_fable/artifacts/obj/fcs/netcoreapp3.0/codegen' is a directory, not a file. [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite) [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.BinaryUtils.CopyFile(String sourcePath, String destinationPath) [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at Microsoft.NET.HostModel.AppHost.HostWriter.CreateAppHost(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String assemblyToCopyResorcesFrom) [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
/usr/local/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(370,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/Users/alfonsogarciacaronunez/dev/fsharp_fable/fcs/fcs-fable/codegen/codegen.fsproj]
```

**Comment by alfonsogarciacaro** [comment]
Sorry, actually `service_slim` did build fine. The error was about the `fable` branch, I've updated the comment above ☝️

**Comment by alfonsogarciacaro** [comment]
[It works!](https://github.com/fable-compiler/Fable/commit/11eeb1cd9ea9487679bafedb9275516166e5ce44) (unfortunately not in the REPL yet until we fixed the issue with fcs-fable).

I've pushed fable-compiler 2.4.0 with support for implicit yields and other F# 4.7 features, thanks again @ncave!

**Comment by michaelsg** [comment]
I just updated to fable-compiler to the latest 2.4.1 and fable-loader to latest, and it says that fable-cli is missing. The bin folder has only a fable-library folder - no fable-cli folder.
I forced all node-modules redownloaded and installed. DLL still missing.

```
$ webpack
Bundling for development...
fable-compiler 2.4.1
child proccess errored: Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-C:\Code2019\Src\FCSTools_Solution\XUI\node_modules\fable-compiler\bin\fable-cli\Fable.Cli.dll does not exist.
```

**Comment by alfonsogarciacaro** [comment]
Yeah, I just realized that 😅 Can you please try with 2.4.2?

**Comment by michaelsg** [comment]
2.4.2 works! Love it!
