### ISSUE TITLE
--port free throws exception

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#946]
### Description

Supplying `--port free` (as per help output) throws an exception.

```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.FSharp.Core.LanguagePrimitives.ParseInt32(String s)
   at Fable.Tools.Main.parseArguments(String[] args)
   at Fable.Tools.Main.main(String[] argv)
```

### Related information 

* fable-compiler version: 1.0.4
* fable-core version: 1.0.4
* Operating system: OSX

**Comment by Zaid-Ajaj** [comment]
Alright, I think the problem was [here](:
```fs
let tryFindArgValue key (args: string[]) =
      match args |> Array.tryFindIndex ((=) key) with
      | Some i -> Some args.[i]
      | None -> None
```
which should be (I committed it by mistake, not tested)
```fs
     let tryFindArgValue key (args: string[]) =
         match args |> Array.tryFindIndex ((=) key) with
        // i is the index of the key
        // i + 1 is the index of arg value
        | Some i -> 
            // if args.[i] is the last element
            if args.Length = i + 1 
            then None 
            else Some args.[i + 1] 
         | None -> None
```

**Comment by alfonsogarciacaro** [comment]
Nice catch @Zaid-Ajaj! Could you please send a PR to fix it?

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Sure thing!

**Comment by alfonsogarciacaro** [comment]
I have published 1.0.5 with the fix, thanks again @Zaid-Ajaj

**Comment by Alxandr** [comment]
Wouldn't it be a good idea to add a unit test to avoid regressions again?

**Comment by alfonsogarciacaro** [comment]
It is! Are you volunteering? :wink:

**Comment by Alxandr** [comment]
While doing random programming things is way funner than writing master thesis, I still should keep on track for the last few weeks :P

**Comment by Zaid-Ajaj** [comment]
Fix was published, I will close this for now, re-open if issue persists

**Comment by Alxandr** [comment]
So, the exception is gone, but now the switch doesn't seem to do anything ^^

```
/Users/alxandr/hub/Fable.Ava/dotnetsdk/dotnet fable node-run --port free "/Users/alxandr/hub/Fable.Ava/build.js"
Cannot start server, please check the port 61225 is free: Address already in use
```

**Comment by Alxandr** [comment]
Ah, sorry, my bad. I had to put it after the js file name.
